// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsjspjfbpchfbngefhdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzanNwamZicGNoZmJuZ2VmaGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODY5NTgsImV4cCI6MjA1OTA2Mjk1OH0.i6V8-3hAzN4BdTmG3qIDjtFDeeGVTnuFVl9QIys3uJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);